---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# patches:
#   - target:
#       kind: AcmeApplication
#       name: foo
#     patch: |-
#       - op: add
#         path: /spec/ingress/hostnames/-
#         value: "subdomain.example.com"
