---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - acme-application.yaml

images:
  - name: ghcr.io/gitops-ci-cd/foo

configurations:
  - image_transformer_config.yaml
